import * as o from '@optique/core';
import { repoFlag } from '../shared.ts';

export default o.command(
  'download',
  o.object({
    action: o.constant('download'),
    runId: o.optional(o.argument(o.string(), { description: o.message`Run ID` })),
    dir: o.option('-D', '--dir', o.string(), { description: o.message`The directory to download artifacts into (default ".")` }),
    name: o.multiple(o.option('-n', '--name', o.string(), { description: o.message`Download artifacts that match any of the given names` })),
    pattern: o.multiple(o.option('-p', '--pattern', o.string(), { description: o.message`Download artifacts that match a glob pattern` })),
    repo: repoFlag,
  }),
  { brief: o.message`Download artifacts generated by a workflow run` },
);
