import '../../base.just'

@_divider *ARGS:
  bun --eval 'console.log("\n\x1b[30;47m" + " " + (process.argv[1] ?? "") + " ".repeat(process.stdout.columns - (process.argv[1]?.length ?? 0) - 1) + "\x1b[0m\n")' "$@"

# Execute all CLI demos, passing the same set of positional arguments and flags
all *ARGS:
  @{{mod}} _divider BROCLI
  bun ./brocli.ts "$@" || true
  @{{mod}} _divider CLIPANION
  bun ./clipanion.ts "$@" || true
  @{{mod}} _divider CMD-TS
  bun ./cmd-ts.ts "$@" || true
  @{{mod}} _divider OPTIQUE
  bun ./optique.ts "$@" || true
  @{{mod}} _divider STRICLI
  bun ./stricli.ts "$@" || true
  @{{mod}} _divider YARGS
  bun ./yargs.ts "$@" || true
  @{{mod}} _divider

brocli *ARGS:
  bun ./brocli.ts "$@"

clipanion *ARGS:
  bun ./clipanion.ts "$@"

cmd-ts *ARGS:
  bun ./cmd-ts.ts "$@"

optique *ARGS:
  bun ./optique.ts "$@"

stricli *ARGS:
  bun ./stricli.ts "$@"

yargs *ARGS:
  bun ./yargs.ts "$@"
